# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.locale_listener:
        class: Proethos2\CoreBundle\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }

    app.response_listener:
        class: Proethos2\CoreBundle\EventListener\ResponseListener
        tags:
           - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension

    logout_success_handler:
        class: Proethos2\CoreBundle\Services\LogoutSuccessHandler
        arguments: ['@security.http_utils']

    app.user_checker_provider:
        class: Proethos2\CoreBundle\Security\UserCheckerProvider